import { Router } from 'express';
import { authRouter } from './modules/auth/auth.routes';
import { activitiesRouter } from './modules/activities/activities.routes';
import { auditRouter } from './modules/audit/audit.routes';
import { catalogsRouter } from './modules/catalogs/catalogs.routes';
import { clientsRouter } from './modules/clients/clients.routes';
import { contactsRouter } from './modules/contacts/contacts.routes';
import { dashboardRouter } from './modules/dashboard/dashboard.routes';
import { documentsRouter } from './modules/documents/documents.routes';
import { notesRouter } from './modules/notes/notes.routes';
import { notificationsRouter } from './modules/notifications/notifications.routes';
import { opportunitiesRouter } from './modules/opportunities/opportunities.routes';
import { productsRouter } from './modules/products/products.routes';
import { prospectsRouter } from './modules/prospects/prospects.routes';
import { quotesRouter } from './modules/quotes/quotes.routes';
import { reportsRouter } from './modules/reports/reports.routes';
import { rolesRouter } from './modules/roles/roles.routes';
import { salesRouter } from './modules/sales/sales.routes';
import { searchRouter } from './modules/search/search.routes';
import { tasksRouter } from './modules/tasks/tasks.routes';
import { settingsRouter } from './modules/settings/settings.routes';
import { teamsRouter } from './modules/teams/teams.routes';
import { usersRouter } from './modules/users/users.routes';

export const apiRouter: Router = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/clients', clientsRouter);
apiRouter.use('/contacts', contactsRouter);
apiRouter.use('/prospects', prospectsRouter);
apiRouter.use('/opportunities', opportunitiesRouter);
apiRouter.use('/quotes', quotesRouter);
apiRouter.use('/sales', salesRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/activities', activitiesRouter);
apiRouter.use('/tasks', tasksRouter);
apiRouter.use('/documents', documentsRouter);
apiRouter.use('/notes', notesRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/teams', teamsRouter);
apiRouter.use('/catalogs', catalogsRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/audit', auditRouter);
